version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: gamescord-db
    restart: always
    environment:
      MYSQL_DATABASE: 'softwareassignmentdb'
      MYSQL_USER: 'taekmin'
      MYSQL_PASSWORD: 'Dlxorals9809!'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  backend:
    build: ./backend # Dockerfile 있는 경로
    container_name: gamescord-backend
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/softwareassignmentdb?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: taekmin
      SPRING_DATASOURCE_PASSWORD: Dlxorals9809!
    depends_on:
      - db

volumes:
  db-data: