version: '3.8'
services:
  app:
    build: .
    container_name: gamescord-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/softwareassignmentdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=taekmin
      - SPRING_DATASOURCE_PASSWORD=Dlxorals9809!
  db:
    image: mysql:8.0
    container_name: gamescord-db
    restart: always
    environment:
      MYSQL_DATABASE: 'softwareassignmentdb'
      MYSQL_USER: 'taekmin'
      MYSQL_PASSWORD: 'Dlxorals9809!'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
volumes:
  db-data: